### ISSUE TITLE
Selfhost zimit

### ISSUE THREAD

**Issue by deimjons** [openzim/zimit-frontend#54]
Hi, folks. I am trying to self-host Zimit. How to configure it with the backend? Here is my docker-compose: 

```
version: '3.9'
services:
  zimit-ui:
    image: ghcr.io/openzim/zimit-ui:latest
    container_name: zimit-ui
    restart: unless-stopped
    labels:
      traefik.enable: true

      traefik.http.routers.zimit-http.rule: Host(`zimit.example.com`)
      traefik.http.routers.zimit-http.entrypoints: web
      traefik.http.routers.zimit-http.middlewares: https-redirect

      traefik.http.routers.zimit-https.rule: Host(`zimit.example.com`)
      traefik.http.routers.zimit-https.entrypoints: websecure
      traefik.http.routers.zimit-https.tls: true
      traefik.http.routers.zimit-https.tls.certresolver: prod
      traefik.http.routers.zimit-https.middlewares: authentik@file

      com.centurylinklabs.watchtower.enable: true
    networks:
      - traefik
      - zimit

  zimit:
    image: ghcr.io/openzim/zimit:zimit2
    container_name: zimit
    restart: unless-stopped
    command: 'zimit --url https://lurkmore.online/ --name lurkmore --workers 2 --waitUntil domcontentloaded'
    shm_size: 1gb
    volumes:
      - output:/output
    networks:
      - zimit
      
volumes:
  output:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $VOLUMES_PATH_PREFIX/zimit/volumes/output

networks:
  zimit:
    name: zimit
  traefik:
    external: true
```
