### ISSUE TITLE
Add solution to check consistency of translations

### ISSUE THREAD

**Issue by benoit74** [openzim/zimit-frontend#72]
With https://github.com/openzim/zimit-frontend/pull/69, we have introduced i18n.

However, currently there is no tooling to ensure consistency:
- identify unused strings (strings present in JSON files but not used - anymore - in JS or Python codebase)
- identify missing strings (strings present in JS or Python codebase but not present in JSON files - must be present in at least `en` for proper operation and in `qqq` for proper TranslateWiki operation)

**Comment by advait-zx** [comment]
Flag any keys that are present in the JSON files but not used in the code
how can i contribute to this issue

**Comment by benoit74** [comment]
I think we first need to check if such a tool does not already exist. Be aware that while all translated strings are stored in JSON files, they are used both in .vue and Jinja2 templates. They could theoretically soon be used in .py files.

If it does not exist, then I would suggest to develop a small Python script doing the job. Be aware that we need both directions, i.e. flag any keys present in the JSON but not used in the code AND flag any keys used in the code but not present in at least `en` and `qqq` JSON files. 

This Python script should exit with non-zero exit code when problem(s) are detected, and we can add this script to invoke `tasks.py` and the the `QA` CI.

I will soon merge #69, so this will be easier to work on.

**Comment by benoit74** [comment]
@advait-zx do you confirm you will work on it, shall I assign you the issue?

**Comment by advait-zx** [comment]
yeah but i will need help for this issue

**Comment by benoit74** [comment]
Isn't what I've described a sufficient start point to make progress and if needed prepare a PR? If not unfortunately I can't help more than that.

**Comment by Prakhar-Shankar** [comment]
Hi @benoit74, can I work on this issue?

**Comment by benoit74** [comment]
Hi @Prakhar-Shankar, sure. Note that at first, no code is needed, you need to search for a tool capable of fulfilling this issue requirements.

**Comment by Prakhar-Shankar** [comment]
Sure, I will first search for the tool, and will try to tell the approach. If the tool does not exist I will try to write a python script. I will try to provide descriptions before committing anything.

**Comment by Prakhar-Shankar** [comment]
Hi @benoit74, I found a tool called vue-i18n-extract. This tool can flag all the string that are unused or are missing. I ran the tool and here is the output - 
![Image](https://github.com/user-attachments/assets/9f2d857b-bf15-4e19-9c79-9e7311935c35)

Also we can make a JSON file where the outputs can be stored.

**Comment by benoit74** [comment]
Seems promising! 

Is it possible to check all languages at once? 

The problem is that :
- some of these keys are in fact used, I don't get why your tool report they are not used, see e.g. https://github.com/openzim/zimit-frontend/blob/e8bac1360065cdb1919a915672aeeafbcd793207/ui/src/stores/main.ts#L137
- some of these keys are used in Python backend, we need  a tool capable to handle both Vue.JS and Python. Or two tools and we merge their results: it might be better to rely on a tool to detect which path are unused because this is probably complex, and then merge their result with a custom tool of our own
- we should be able to ignore some key(s): for now, `language` is not used on purpose
- it seems to do only the first point of my initial comment ; we need to do the other direction as well (check which path are used in the code but are not present in at least `qqq` and `en`)

Note that we need to integrate this check to the CI, so we need to check all languages and we need a clean return code (different than 0 when there is a problem, so that it will fail the CI).

**Comment by Prakhar-Shankar** [comment]
Got it, the issue with this tool is, it can check only .vue files and not the python files. 
I am still searching for a tool which can analyze the python files as well.

Therefore, we may have to use two different tools and later combine the result as you said. If nothing works out we may have to write a python script to check the .py files. 

Coming to your third point, this tool is capable of finding missing keys as well, I don't know why I didn't work, I will surely work on it and verify the process. Also I will keep in mind about the CI part.
Thanks for the instructions, I will try to get the solution soon.

**Comment by Prakhar-Shankar** [comment]
Hii @benoit74 , I have been extensively searching for similar tool which can be helpful with the .py files but, I think there is not any tool available at this moment.

**Comment by benoit74** [comment]
OK, then we will have to build our own logic in Python, probably based on regexp. Luckily in Python we do not have many pattern (we use either `i18n.t` in Python code or `translate` in Jinja2 templates - and currently only Jinja2 templates in fact), and supporting only what we use is OK in a first version.

Given that we want to have an overview of both Python and Vue.JS usage, and Vue.JS usage is also limited to few patterns, I wonder if it doesn't make more sense to search for labels used only with our custom Python script for both languages, and avoid spending time integrating `vue-i18n-extract` results with Python results. No strong opinion, on my side, more an open question. WDYT?

**Comment by Prakhar-Shankar** [comment]
Yes, I think if we are building a python script, we can use it for both kind of files(if we face any issue then we already have a tool for .vue which can be used anytime). I will try my best to implement these.
Thanks a lot.

**Comment by benoit74** [comment]
Thank you

A first feedback:
- please add an option to ignore some known unused keys, `language` and `@metadata` so far, ignoring the key itself and all its children )
- faq, unit, ... are used (they have children) so they should not be reported as unused
- I did not checked all missing keys, but I'm pretty sure most of them do exists
- the missing `.`, `id` and `key` keys looks like parsing bugs

Note that you do not need to paste screenshots, you can simply copy-paste text?

**Comment by Prakhar-Shankar** [comment]
sure thanks a lot for guiding me. I will look into it.

**Comment by Prakhar-Shankar** [comment]
I have improved the code, and this is the output I am getting as of now- 
```
Unused localization keys:
  fa.json:
    - faq.whatIsZimDescParagraph
    - faq.howToReadDescParagraph
    - faq.missingContentDesc
    - faq.gotErrorDescParagraph
    - footer.poweredByThankTo
    - newRequest.headingParagraph
    - requestStatus.progressMessage
    - requestStatus.refreshAuto
    - requestStatus.failureReasons
    - requestStatus.limitHit
    - email.requested.subject
    - email.requested.title
    - email.requested.zimRequestRecorded
    - email.requested.howToFollowProgress
    - email.requested.emailWillBeSent
    - email.succeeded.subject
    - email.succeeded.title
    - email.succeeded.zimRequestCompleted
    - email.succeeded.hereItIs
    - email.succeeded.incomplete
    - email.succeeded.contactUsLinkContent
    - email.failed.subject
    - email.failed.title
    - email.failed.weAreSorry
    - email.failed.checkAndRetry
    - email.failed.retryLinkContent
    - email.failed.howToCheckSettings
  id.json:
    - faq.whatIsZimDescParagraph
    - faq.howToReadDescParagraph
    - faq.missingContentDesc
    - faq.gotErrorDescParagraph
    - footer.poweredByThankTo
    - newRequest.headingParagraph
    - requestStatus.progressMessage
    - requestStatus.refreshAuto
    - requestStatus.failureReasons
    - requestStatus.limitHit
    - email.requested.subject
    - email.requested.title
    - email.requested.zimRequestRecorded
    - email.requested.howToFollowProgress
    - email.requested.emailWillBeSent
    - email.succeeded.subject
    - email.succeeded.title
    - email.succeeded.zimRequestCompleted
    - email.succeeded.hereItIs
    - email.succeeded.incomplete
    - email.succeeded.contactUsLinkContent
    - email.failed.subject
    - email.failed.title
    - email.failed.weAreSorry
    - email.failed.checkAndRetry
    - email.failed.retryLinkContent
    - email.failed.howToCheckSettings
  lb.json:
    - requestStatus.progressMessage
    - requestStatus.refreshAuto
    - email.requested.subject
    - email.requested.title
    - email.requested.zimRequestRecorded
    - email.requested.howToFollowProgress
    - email.requested.emailWillBeSent
    - email.succeeded.subject
    - email.succeeded.title
    - email.succeeded.zimRequestCompleted
    - email.succeeded.hereItIs
    - email.succeeded.contactUsLinkContent
    - email.failed.subject
    - email.failed.title
    - email.failed.weAreSorry
    - email.failed.retryLinkContent
    - email.failed.howToCheckSettings
  fr.json:
    - faq.whatIsZimDescParagraph
    - faq.howToReadDescParagraph
    - faq.missingContentDesc
    - faq.gotErrorDescParagraph
    - footer.poweredByThankTo
    - newRequest.headingParagraph
    - requestStatus.progressMessage
    - requestStatus.refreshAuto
    - requestStatus.failureReasons
    - requestStatus.limitHit
    - email.requested.subject
    - email.requested.title
    - email.requested.zimRequestRecorded
    - email.requested.howToFollowProgress
    - email.requested.emailWillBeSent
    - email.succeeded.subject
    - email.succeeded.title
    - email.succeeded.zimRequestCompleted
    - email.succeeded.hereItIs
    - email.succeeded.incomplete
    - email.succeeded.contactUsLinkContent
    - email.failed.subject
    - email.failed.title
    - email.failed.weAreSorry
    - email.failed.checkAndRetry
    - email.failed.retryLinkContent
    - email.failed.howToCheckSettings
  qqq.json:
    - faq.whatIsZimDescParagraph
    - faq.howToReadDescParagraph
    - faq.missingContentDesc
    - faq.gotErrorDescParagraph
    - footer.poweredByThankTo
    - newRequest.headingParagraph
    - requestStatus.progressMessage
    - requestStatus.refreshAuto
    - requestStatus.failureReasons
    - requestStatus.limitHit
    - email.requested.subject
    - email.requested.title
    - email.requested.zimRequestRecorded
    - email.requested.howToFollowProgress
    - email.requested.emailWillBeSent
    - email.succeeded.subject
    - email.succeeded.title
    - email.succeeded.zimRequestCompleted
    - email.succeeded.hereItIs
    - email.succeeded.incomplete
    - email.succeeded.contactUsLinkContent
    - email.failed.subject
    - email.failed.title
    - email.failed.weAreSorry
    - email.failed.checkAndRetry
    - email.failed.retryLinkContent
    - email.failed.howToCheckSettings
  ko.json:
    - newRequest.headingParagraph
    - requestStatus.progressMessage
    - requestStatus.refreshAuto
    - email.requested.subject
    - email.requested.title
    - email.requested.zimRequestRecorded
    - email.requested.howToFollowProgress
    - email.requested.emailWillBeSent
    - email.succeeded.subject
    - email.succeeded.title
    - email.succeeded.zimRequestCompleted
    - email.succeeded.hereItIs
    - email.succeeded.contactUsLinkContent
    - email.failed.subject
    - email.failed.title
    - email.failed.weAreSorry
    - email.failed.checkAndRetry
    - email.failed.retryLinkContent
    - email.failed.howToCheckSettings
  sq.json:
    - faq.whatIsZimDescParagraph
    - faq.howToReadDescParagraph
    - faq.missingContentDesc
    - faq.gotErrorDescParagraph
    - footer.poweredByThankTo
    - newRequest.headingParagraph
    - requestStatus.progressMessage
    - requestStatus.refreshAuto
    - requestStatus.failureReasons
    - requestStatus.limitHit
    - email.requested.subject
    - email.requested.title
    - email.requested.zimRequestRecorded
    - email.requested.howToFollowProgress
    - email.requested.emailWillBeSent
    - email.succeeded.subject
    - email.succeeded.title
    - email.succeeded.zimRequestCompleted
    - email.succeeded.hereItIs
    - email.succeeded.incomplete
    - email.succeeded.contactUsLinkContent
    - email.failed.subject
    - email.failed.title
    - email.failed.weAreSorry
    - email.failed.checkAndRetry
    - email.failed.retryLinkContent
    - email.failed.howToCheckSettings
  mk.json:
    - faq.whatIsZimDescParagraph
    - faq.howToReadDescParagraph
    - faq.gotErrorDescParagraph
    - footer.poweredByThankTo
    - newRequest.headingParagraph
    - requestStatus.progressMessage
    - requestStatus.refreshAuto
    - email.requested.howToFollowProgress
    - email.requested.emailWillBeSent
    - email.succeeded.subject
    - email.succeeded.title
    - email.succeeded.zimRequestCompleted
    - email.succeeded.hereItIs
    - email.succeeded.incomplete
    - email.succeeded.contactUsLinkContent
    - email.failed.subject
    - email.failed.title
    - email.failed.weAreSorry
    - email.failed.checkAndRetry
    - email.failed.retryLinkContent
    - email.failed.howToCheckSettings
  zh-hans.json:
    - faq.whatIsZimDescParagraph
    - faq.howToReadDescParagraph
    - faq.missingContentDesc
    - faq.gotErrorDescParagraph
    - footer.poweredByThankTo
    - newRequest.headingParagraph
    - requestStatus.progressMessage
    - requestStatus.refreshAuto
    - requestStatus.failureReasons
    - requestStatus.limitHit
    - email.requested.subject
    - email.requested.title
    - email.requested.zimRequestRecorded
    - email.requested.howToFollowProgress
    - email.requested.emailWillBeSent
    - email.succeeded.subject
    - email.succeeded.title
    - email.succeeded.zimRequestCompleted
    - email.succeeded.hereItIs
    - email.succeeded.incomplete
    - email.succeeded.contactUsLinkContent
    - email.failed.subject
    - email.failed.title
    - email.failed.weAreSorry
    - email.failed.checkAndRetry
    - email.failed.retryLinkContent
    - email.failed.howToCheckSettings
  he.json:
    - faq.whatIsZimDescParagraph
    - faq.howToReadDescParagraph
    - faq.missingContentDesc
    - faq.gotErrorDescParagraph
    - footer.poweredByThankTo
    - newRequest.headingParagraph
    - requestStatus.refreshAuto
    - requestStatus.failureReasons
    - requestStatus.limitHit
  en.json:
    - faq.whatIsZimDescParagraph
    - faq.howToReadDescParagraph
    - faq.missingContentDesc
    - faq.gotErrorDescParagraph
    - footer.poweredByThankTo
    - newRequest.headingParagraph
    - requestStatus.progressMessage
    - requestStatus.refreshAuto
    - requestStatus.failureReasons
    - requestStatus.limitHit
    - email.requested.subject
    - email.requested.title
    - email.requested.zimRequestRecorded
    - email.requested.howToFollowProgress
    - email.requested.emailWillBeSent
    - email.succeeded.subject
    - email.succeeded.title
    - email.succeeded.zimRequestCompleted
    - email.succeeded.hereItIs
    - email.succeeded.incomplete
    - email.succeeded.contactUsLinkContent
    - email.failed.subject
    - email.failed.title
    - email.failed.weAreSorry
    - email.failed.checkAndRetry
    - email.failed.retryLinkContent
    - email.failed.howToCheckSettings
  es.json:
    - faq.whatIsZimDescParagraph
    - faq.howToReadDescParagraph
    - faq.missingContentDesc
    - faq.gotErrorDescParagraph
    - footer.poweredByThankTo
    - newRequest.headingParagraph
    - requestStatus.progressMessage
    - requestStatus.refreshAuto
    - requestStatus.failureReasons
    - requestStatus.limitHit
    - email.requested.subject
    - email.requested.title
    - email.requested.zimRequestRecorded
    - email.requested.howToFollowProgress
    - email.requested.emailWillBeSent
    - email.succeeded.subject
    - email.succeeded.title
    - email.succeeded.zimRequestCompleted
    - email.succeeded.hereItIs
    - email.succeeded.incomplete
    - email.succeeded.contactUsLinkContent
    - email.failed.subject
    - email.failed.title
    - email.failed.weAreSorry
    - email.failed.checkAndRetry
    - email.failed.retryLinkContent
    - email.failed.howToCheckSettings

Missing localization keys:
  - refresh_token
  - access_token
  - requested
  
```

I have made an array of ignored keys, we can make a separate .txt file for that if we want. Also I have checked the parsing bugs.
